# Generated by Django 4.1.7 on 2023-03-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.FloatField()),
                ('Object_Rating', models.IntegerField()),
                ('BodyPart_Rating', models.IntegerField()),
                ('Gender', models.IntegerField()),
                ('Delivery', models.IntegerField()),
                ('Birth_Injury', models.IntegerField()),
                ('Jaundice', models.IntegerField()),
                ('Cousin_Marriage', models.IntegerField()),
                ('Q1', models.IntegerField()),
                ('Q2', models.IntegerField()),
                ('Q3', models.IntegerField()),
                ('Q4', models.IntegerField()),
                ('Q5', models.IntegerField()),
                ('Q6', models.IntegerField()),
                ('Q7', models.IntegerField()),
                ('Q8', models.IntegerField()),
                ('Q9', models.IntegerField()),
                ('Q10', models.IntegerField()),
                ('Q11', models.IntegerField()),
                ('classification', models.CharField(max_length=30)),
            ],
        ),
    ]
